/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Thu Nov  8 11:02:38 2018. */

#include "simple_pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SimpleMessage, lucky_number, lucky_number, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
